# Objetivo da Análise

O objetivo desta análise é demonstrar que variáveis como o número de dependentes, profissão e idade não são fundamentais para definir se o usuário terá uma boa gestão do seu dinheiro.

---

## Metodologia

Analisaremos essas variáveis em relação ao **Savings Ratio** (Taxa de Economia), que busca identificar quanto da renda está sendo "perdido" em gastos supérfluos.

---

## O que o seu "Percentual" realmente significa?

O cálculo soma gastos com lazer, alimentação fora e outros itens não essenciais. Portanto:

- **Percentual ALTO (Ex: 40%):** Indica que a pessoa é **ineficiente financeiramente**. Ela gasta quase metade do que ganha com itens não essenciais. Existe um enorme "potencial" de economia sendo desperdiçado.

- **Percentual BAIXO (Ex: 5%):** Indica que a pessoa é **eficiente**. O orçamento está tão ajustado que quase não sobra margem para cortar gastos supérfluos.

---

## Ferramenta de Visualização: Gráfico de Violino

Utilizaremos como base o **gráfico de violino**. No eixo Y, ele mostra a densidade dos dados, facilitando a visualização de grandes volumes de informações que estariam sobrepostas em outros tipos de gráfico.

Esse primeiro arquivo serve para a visualização de dados

In [1]:
import pandas as pd


#renda tier da cidade e transport
#carregando a base de dados 
dados = pd.read_csv('../../dataset/data.csv')

#printando a base de dados
display(dados)

,Income,Age,Dependents,Occupation,City_Tier,Rent,Loan_Repayment,Insurance,Groceries,Transport,...,Desired_Savings,Disposable_Income,Potential_Savings_Groceries,Potential_Savings_Transport,Potential_Savings_Eating_Out,Potential_Savings_Entertainment,Potential_Savings_Utilities,Potential_Savings_Healthcare,Potential_Savings_Education,Potential_Savings_Miscellaneous
0,44637.249636,49,0,Self_Employed,Tier_1,13391.174891,0.000000,2206.490129,6658.768341,2636.970696,...,6200.537192,11265.627707,1685.696222,328.895281,465.769172,195.151320,678.292859,67.682471,0.000000,85.735517
1,26858.596592,34,2,Retired,Tier_2,5371.719318,0.000000,869.522617,2818.444460,1543.018778,...,1923.176434,9676.818733,540.306561,119.347139,141.866089,234.131168,286.668408,6.603212,56.306874,97.388606
2,50367.605084,35,1,Student,Tier_3,7555.140763,4612.103386,2201.800050,6313.222081,3221.396403,...,7050.360422,13891.450624,1466.073984,473.549752,410.857129,459.965256,488.383423,7.290892,106.653597,138.542422
3,101455.600247,21,0,Self_Employed,Tier_3,15218.340037,6809.441427,4889.418087,14690.149363,7106.130005,...,16694.965136,31617.953615,1875.932770,762.020789,1241.017448,320.190594,1389.815033,193.502754,0.000000,296.041183
4,24875.283548,52,4,Professional,Tier_2,4975.056710,3112.609398,635.907170,3034.329665,1276.155163,...,1874.099434,6265.700532,788.953124,68.160766,61.712505,187.173750,194.117130,47.294591,67.388120,96.557076
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,40913.466178,51,4,Self_Employed,Tier_1,12274.039853,7703.854895,1646.799940,5477.403246,2084.230191,...,1163.318310,1163.318310,597.028412,287.315050,347.658355,145.843671,212.833325,44.900294,98.765527,190.591917
19996,90295.772638,21,1,Student,Tier_2,18059.154528,0.000000,2770.589626,13118.222419,4633.108332,...,10613.589598,30725.175170,3854.823822,359.602765,911.269461,424.064224,1555.548024,129.655981,239.445622,351.436046
19997,40604.567373,30,1,Professional,Tier_2,8120.913475,8089.612716,1548.564328,6018.276121,2493.563674,...,2267.905134,2267.905134,1385.511100,379.927216,138.209465,297.695658,824.565267,57.891000,72.728663,122.569277
19998,118157.817240,27,2,Professional,Tier_1,35447.345172,12345.910538,4735.672471,16392.438426,8248.242279,...,10603.684814,10603.684814,3217.771594,2265.865033,726.247719,273.912367,859.230004,98.961780,92.189012,569.811212
19999,8209.249769,62,3,Professional,Tier_1,2462.774931,1120.881704,276.376556,969.916908,460.435438,...,531.044006,860.350559,261.160294,124.057428,25.940556,35.238134,94.909265,1.685026,4.837574,12.766302

Aqui estamos vendo as descrições dos dados(para analisar se existe alguma coluna vazia) e vendo dados como 

count--contagem de cada coluna(bom para ver se existe dados ociosos)
#não temos nenhum dado ocioso
#caso tivesse --> dados_atualizados=dados.drop(index="linha") excluir uma linha em específico

mean-- méida
std--desvio padrão da média
min-valor mínimo dos dados da coluna
max-valor máximo

porcentagens de partes da base de dados


Além disso a partir do método info é possível vermos quais são so tipos de dados de cada coluna

In [2]:
display(dados.describe())



#retorna os tipos de dados de cada tabela
display(dados.info())

,Income,Age,Dependents,Rent,Loan_Repayment,Insurance,Groceries,Transport,Eating_Out,Entertainment,...,Desired_Savings,Disposable_Income,Potential_Savings_Groceries,Potential_Savings_Transport,Potential_Savings_Eating_Out,Potential_Savings_Entertainment,Potential_Savings_Utilities,Potential_Savings_Healthcare,Potential_Savings_Education,Potential_Savings_Miscellaneous
count,2.000000e+04,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,...,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000
mean,4.158550e+04,41.031450,1.995950,9115.494629,2049.800292,1455.028761,5205.667493,2704.466685,1461.856982,1448.853658,...,4982.878416,10647.367257,912.197183,473.042650,254.963280,254.031058,436.332808,41.524964,62.417083,144.904987
std,4.001454e+04,13.578725,1.417616,9254.228188,4281.789941,1492.938435,5035.953689,2666.345648,1481.660811,1489.019270,...,7733.468188,11740.637289,1038.884968,537.222853,296.047943,299.973590,503.200658,53.152458,98.842656,169.160951
min,1.301187e+03,18.000000,0.000000,235.365692,0.000000,30.002012,154.078240,81.228584,39.437523,45.421469,...,0.000000,-5400.788673,16.575501,8.268076,3.797926,3.121610,6.200297,0.001238,0.000000,2.091973
25%,1.760488e+04,29.000000,1.000000,3649.422246,0.000000,580.204749,2165.426419,1124.578012,581.011801,581.632906,...,1224.932636,3774.894323,317.811000,161.913751,84.506870,84.562090,148.013618,11.037421,4.926210,47.637307
50%,3.018538e+04,41.000000,2.000000,6402.751824,0.000000,1017.124681,3741.091535,1933.845509,1029.109726,1020.198376,...,2155.356763,7224.890977,607.038735,307.045856,164.927660,164.740232,285.739582,25.202124,33.127987,93.090257
75%,5.176545e+04,53.000000,3.000000,11263.940492,2627.142320,1787.160895,6470.892718,3360.597508,1807.075251,1790.104082,...,6216.309609,13331.950716,1128.681837,588.419602,313.398240,310.927935,538.983703,52.353736,80.946145,178.257981
max,1.079728e+06,64.000000,4.000000,215945.674703,123080.682009,38734.932935,119816.898124,81861.503457,34406.100166,38667.368308,...,245504.485208,377060.218482,34894.644404,12273.258242,5573.036433,6222.200913,8081.799518,1394.531049,3647.244243,4637.951137

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 27 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Income                           20000 non-null  float64
 1   Age                              20000 non-null  int64
 2   Dependents                       20000 non-null  int64
 3   Occupation                       20000 non-null  object
 4   City_Tier                        20000 non-null  object
 5   Rent                             20000 non-null  float64
 6   Loan_Repayment                   20000 non-null  float64
 7   Insurance                        20000 non-null  float64
 8   Groceries                        20000 non-null  float64
 9   Transport                        20000 non-null  float64
 10  Eating_Out                       20000 non-null  float64
 11  Entertainment                    20000 non-null  float64
 12  Utilities                        20000 non-null  float64
 13  Healthcare                       20000 non-null  float64
 14  Education                        20000 non-null  float64
 15  Miscellaneous                    20000 non-null  float64
 16  Desired_Savings_Percentage       20000 non-null  float64
 17  Desired_Savings                  20000 non-null  float64
 18  Disposable_Income                20000 non-null  float64
 19  Potential_Savings_Groceries      20000 non-null  float64
 20  Potential_Savings_Transport      20000 non-null  float64
 21  Potential_Savings_Eating_Out     20000 non-null  float64
 22  Potential_Savings_Entertainment  20000 non-null  float64
 23  Potential_Savings_Utilities      20000 non-null  float64
 24  Potential_Savings_Healthcare     20000 non-null  float64
 25  Potential_Savings_Education      20000 non-null  float64
 26  Potential_Savings_Miscellaneous  20000 non-null  float64
dtypes: float64(23), int64(2), object(2)
memory usage: 4.1+ MB

None

## 4.1. Análise: Potencial de Economia vs. Dependentes
A análise indica que pessoas sem dependentes tendem a apresentar melhores índices de potencial de economia. No entanto, ao observar a densidade, notamos que a grande massa de dados se concentra de forma muito semelhante entre os grupos.

> Utilizamos o método `update_traces(scalemode='count')` com o objetivo de deixar o violino com o tamanho real da quantidade de dados e, mesmo assim, podemos observar que a **"grande massa"** das pessoas que têm **0 dependentes** e das pessoas que têm **4 dependentes** está concentrada mais ou menos na mesma área.

**O número de dependentes influencia o orçamento, mas não é o fator fundamental**. A concentração de pessoas com 0 ou 4 dependentes permanece majoritariamente na mesma faixa percentual de gastos.

In [6]:
import plotly.express as px

#lista vai servir para somar os valores
colunas_economia = [
    'Potential_Savings_Groceries', 'Potential_Savings_Transport', 
    'Potential_Savings_Eating_Out', 'Potential_Savings_Entertainment', 
    'Potential_Savings_Utilities', 'Potential_Savings_Healthcare', 
    'Potential_Savings_Education', 'Potential_Savings_Miscellaneous'
]
#criando nova coluna em relação aos gastos
dados['Potential_Savings'] = dados[colunas_economia].sum(axis=1)
#calculando o índice de 'gasto desnecessário'
dados['waste_Ratio'] = (dados['Potential_Savings'] / dados['Income']) * 100

#necessário passar apra string para que o plotly divida em categorias

dados['Dependents_Str'] = dados['Dependents'].astype(str)

# 3. Gerando o Violin Plot por Dependentes
fig = px.violin(
    dados, 
    x="Dependents_Str", #eixo x=classificação dependentes
    y="waste_Ratio",  #eixo y=% de de gasto que poderiam ser evitados
    color="Dependents_Str", 
    box=True,          
    points="all",      
    #ordenando para que fique visivelmente melhor
    category_orders={"Dependents_Str": sorted(dados['Dependents_Str'].unique())},
    title="Distribuição de Potencial Economia:Distribuição por número de dependentes",
    labels={
        "Dependents_Str": "Número de Dependentes",
        "waste_Ratio": "% de Economia sobre a Renda"
    },
    template="plotly_white"
)
# linha da média para comparar com a mediana (boxplot interno)
fig.update_traces(meanline_visible=True)

#esse método é responsávell por deixar o violino no tamanho real,sem haver distorções na imagem,mesmo se os outros
#forem maiores
fig.update_traces(scalemode='count')
#linhas de guia 
fig.update_layout(
    hovermode="x", # Faz a linha focar no grupo (eixo X) onde o mouse está
    yaxis=dict(
        showspikes=True, #ativa a linha de guia
        spikemode="across", #faz a linha atravessar o gráfico inteiro
        spikesnap="cursor", #a linha segue exatamente o mouse, não "pula" nos pontos
        spikethickness=2, #espessura da linha
        spikedash="dash", #estilo da linha 
        spikecolor="gray" 
    )
)


fig.show()

## 4.2. Análise: Potencial de Economia x Idade
O comportamento por faixa etária assemelha-se ao de dependentes. Embora o grupo de idosos possua uma amostra significativamente maior no dataset, a densidade do comportamento financeiro (onde o violino é mais "gordo") é muito parecida com as demais idades.

Mesmo com o avanço da idade, a **densidade de gastos supérfluos mantém um padrão, reforçando que a idade não determina a maturidade financeira no consumo.**

In [7]:
import pandas as pd
import plotly.express as px


colunas_economia = [
    'Potential_Savings_Groceries', 'Potential_Savings_Transport', 
    'Potential_Savings_Eating_Out', 'Potential_Savings_Entertainment', 
    'Potential_Savings_Utilities', 'Potential_Savings_Healthcare', 
    'Potential_Savings_Education', 'Potential_Savings_Miscellaneous'
]


dados['Potential_Savings'] = dados[colunas_economia].sum(axis=1)
dados['waste_Ratio'] = (dados['Potential_Savings'] / dados['Income']) * 100

#criando a faixa etaria
bins = [0, 18, 31, 46, 61, 100]
labels_idade = ['Jovem', 'Jovem Adulto', 'Adulto', 'Sênior', 'Idoso']
dados['Age_Group'] = pd.cut(dados['Age'], bins=bins, labels=labels_idade, right=False)


fig = px.violin(
    dados, 
    x="Age_Group", 
    y="waste_Ratio", 
    color="Age_Group", 
    box=True,            
    points='all',         
    category_orders={"Age_Group": labels_idade},
    title="Distribuição de Potencial Economia:Distribuição por Idade",
    labels={
        "Age_Group": "Faixa Etária",
        "waste_Ratio": "% de Economia sobre a Renda"
    },
    template="plotly_white"
)

# linha da média para comparar com a mediana (boxplot interno)
fig.update_traces(meanline_visible=True)

#esse método é responsávell por deixar o violino no tamanho real,sem haver distorções na imagem,mesmo se os outros
#forem maiores
fig.update_traces(scalemode='count')
#linhas de guia 
fig.update_layout(
    hovermode="x", # Faz a linha focar no grupo (eixo X) onde o mouse está
    yaxis=dict(
        showspikes=True, #ativa a linha de guia
        spikemode="across", #faz a linha atravessar o gráfico inteiro
        spikesnap="cursor", #a linha segue exatamente o mouse, não "pula" nos pontos
        spikethickness=2, #espessura da linha
        spikedash="dash", #estilo da linha 
        spikecolor="gray" 
    )
)

fig.show()



## 4.3. Análise: Potencial de Economia x Ocupação
Nesta última análise, verificamos a relação entre a profissão e a gestão da renda. O padrão observado anteriormente se repete: a maior densidade de dados converge para a mesma porcentagem, independentemente do cargo ocupado.

**A ocupação influencia o volume de renda, mas não é o fator determinante para a eficiência do gasto.**

In [8]:
import plotly.express as px


colunas_economia = [
    'Potential_Savings_Groceries', 'Potential_Savings_Transport', 
    'Potential_Savings_Eating_Out', 'Potential_Savings_Entertainment', 
    'Potential_Savings_Utilities', 'Potential_Savings_Healthcare', 
    'Potential_Savings_Education', 'Potential_Savings_Miscellaneous'
]
dados['Potential_Savings'] = dados[colunas_economia].sum(axis=1)
dados['waste_Ratio'] = (dados['Potential_Savings'] / dados['Income']) * 100

ordem_ocupacao = ['Estudante', 'CLT', 'Autônomo', 'Aposentado']


fig = px.violin(
    dados, 
    x="Occupation",      
    y="waste_Ratio", 
    color="Occupation", 
    box=True,          
    points="all",      
    category_orders={"Occupation": ordem_ocupacao}, 
    title="Análise de Potencial de Economia: Distribuição por Ocupação",
    labels={
        "Occupation": "Tipo de Ocupação",
        "waste_Ratio": "% de Economia Potencial"
    },
    template="plotly_white"
)
# linha da média para comparar com a mediana (boxplot interno)
fig.update_traces(meanline_visible=True)

#esse método é responsávell por deixar o violino no tamanho real,sem haver distorções na imagem,mesmo se os outros
#forem maiores
fig.update_traces(scalemode='count')
#linhas de guia 
fig.update_layout(
    hovermode="x", # Faz a linha focar no grupo (eixo X) onde o mouse está
    yaxis=dict(
        showspikes=True, #ativa a linha de guia
        spikemode="across", #faz a linha atravessar o gráfico inteiro
        spikesnap="cursor", #a linha segue exatamente o mouse, não "pula" nos pontos
        spikethickness=2, #espessura da linha
        spikedash="dash", #estilo da linha 
        spikecolor="gray" 
    )
)


fig.show()


## 5. Conclusão Geral
Dessa forma, concluímos que variáveis como idade, ocupação e número de dependentes exercem influência sobre o orçamento, mas não são fatores determinantes para a eficiência financeira.

O verdadeiro fator decisivo parece ser o **nível de educação financeira**. A falta de uma base educacional sólida sobre finanças gera um padrão de consumo comum entre diferentes grupos sociais. Isso faz com que indivíduos de perfis completamente distintos acabem apresentando o mesmo comportamento de gastos ineficientes, criando um "padrão social" de desperdício financeiro.